
### Basic information
site_name: freedomhouse
theme:
  name: readthedocs

### Repo information
repo_url: https://github.com/pachadotdev/freedomhouse
repo_name: freedomhouse

### Plugins
plugins:
  - search

### Navigation tree
nav:
  - Home: README.md
  - Reference: reference.md
  - License: LICENSE.md
    
